/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Performance;
import Players.*;
import javax.swing.AbstractButton;
import javax.swing.JComponent;

/**
 *
 * @author Khedr
 */
public class Performance_main extends javax.swing.JPanel {

    /**
     * Creates new form Teams_main
     */
    public Performance_main() {
        initComponents();
        removeButtonDefault(addPerformance);
        removeButtonDefault(viewPerformance);
        removeButtonDefault(modifyPerformance);
        removeButtonDefault(removePerformance);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addPerformance = new javax.swing.JButton();
        modifyPerformance = new javax.swing.JButton();
        removePerformance = new javax.swing.JButton();
        viewPerformance = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(55, 0, 60));
        setMinimumSize(new java.awt.Dimension(1155, 525));
        setLayout(null);

        addPerformance.setFont(new java.awt.Font("Segoe UI Variable", 1, 16)); // NOI18N
        addPerformance.setText("Log Player Performance");
        addPerformance.setBorder(null);
        addPerformance.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addPerformance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPerformanceActionPerformed(evt);
            }
        });
        add(addPerformance);
        addPerformance.setBounds(70, 210, 200, 70);

        modifyPerformance.setFont(new java.awt.Font("Segoe UI Variable", 1, 16)); // NOI18N
        modifyPerformance.setText("Correct Performance info");
        modifyPerformance.setBorder(null);
        modifyPerformance.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        modifyPerformance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyPerformanceActionPerformed(evt);
            }
        });
        add(modifyPerformance);
        modifyPerformance.setBounds(600, 210, 200, 70);

        removePerformance.setFont(new java.awt.Font("Segoe UI Variable", 1, 16)); // NOI18N
        removePerformance.setText("Remove incorrect records");
        removePerformance.setBorder(null);
        removePerformance.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        removePerformance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removePerformanceActionPerformed(evt);
            }
        });
        add(removePerformance);
        removePerformance.setBounds(860, 210, 200, 70);

        viewPerformance.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        viewPerformance.setText("View Player Stats");
        viewPerformance.setBorder(null);
        viewPerformance.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewPerformance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPerformanceActionPerformed(evt);
            }
        });
        add(viewPerformance);
        viewPerformance.setBounds(330, 210, 200, 70);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/transparentBackground.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1);
        jLabel1.setBounds(0, 0, 1140, 530);
    }// </editor-fold>//GEN-END:initComponents

    private void addPerformanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPerformanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addPerformanceActionPerformed

    private void modifyPerformanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyPerformanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modifyPerformanceActionPerformed

    private void removePerformanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removePerformanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_removePerformanceActionPerformed

    private void viewPerformanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPerformanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewPerformanceActionPerformed

        private void removeButtonDefault(JComponent component) {
        if (component instanceof AbstractButton) {
            AbstractButton button = (AbstractButton) component;
            button.setContentAreaFilled(false);
            button.setOpaque(true);
            button.setBorderPainted(false);
            button.setFocusPainted(false);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPerformance;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton modifyPerformance;
    private javax.swing.JButton removePerformance;
    private javax.swing.JButton viewPerformance;
    // End of variables declaration//GEN-END:variables
}
